/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package org.uv.dapp01practica01;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persisten/*
//// * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
//// * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
//// */
////package org.uv.bdnc_practica01;
////
////import java.sql.Connection;
////import java.sql.DriverManager;
////import java.sql.PreparedStatement;
////import java.sql.ResultSet;
////import java.sql.SQLException;
////import java.sql.Statement;
////import java.util.logging.Level;
////import java.util.logging.Logger;
////import javax.swing.JOptionPane;
////import javax.swing.table.DefaultTableModel;
////
/////**
//// *
//// * @author francisco
//// */
////public class Empleados extends javax.swing.JInternalFrame {
////
////    /**
////     * Creates new form Empleados
////     */
////
////    public Empleados() throws SQLException {
////        initComponents();
////       lista();
////    }
////
////    /**
////     * This method is called from within the constructor to initialize the form.
////     * WARNING: Do NOT modify this code. The content of this method is always
////     * regenerated by the Form Editor.
////     */
////    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Clave = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        Departamento = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setMinimumSize(new java.awt.Dimension(560, 130));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, -1, -1));

        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        Clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaveActionPerformed(evt);
            }
        });
        getContentPane().add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 180, -1));
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 180, -1));

        Telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelefonoActionPerformed(evt);
            }
        });
        getContentPane().add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 180, -1));
        getContentPane().add(Departamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 180, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Clave", "Nombre"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 380, 180));
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 180, -1));

        jLabel1.setText("Clave");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3.setText("Direccion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setText("Departamento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        pack();
    }// </editor-fold>                        

    private void TelefonoActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      PojoEmpleado empleado = new PojoEmpleado();
      DaoEmpleado daoempleado = new DaoEmpleado();
      empleado.setClave(Integer.parseInt(Clave.getText()));
      empleado.setNombre(Nombre.getText());
      empleado.setDireccion(Direccion.getText());
      empleado.setTelefono(Telefono.getText());
      empleado.setDepartamento(Integer.parseInt(Departamento.getText()));
      boolean guardado = daoempleado.guardar(empleado);
      
      if (guardado==true) {
        JOptionPane.showMessageDialog(this, "Se guardo correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Error al guardarr el registro", "Error", JOptionPane.ERROR_MESSAGE);
    }
      
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      PojoEmpleado empleado = new PojoEmpleado();
      DaoEmpleado daoempleado = new DaoEmpleado();
      empleado.setClave(Integer.parseInt(Clave.getText()));
      empleado.setNombre(Nombre.getText());
      empleado.setDireccion(Direccion.getText());
      empleado.setTelefono(Telefono.getText());
      empleado.setDepartamento(Integer.parseInt(Departamento.getText()));
     boolean editado= daoempleado.editar(empleado);
      if (editado==true) {
        JOptionPane.showMessageDialog(this, "Se edito correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Error al editar el registro", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
      PojoEmpleado empleado = new PojoEmpleado();
      DaoEmpleado daoempleado = new DaoEmpleado();
      empleado = daoempleado.buscarid(Integer.parseInt(Clave.getText()));
      Nombre.setText(empleado.getNombre());
      Direccion.setText(empleado.getDireccion());
      Telefono.setText(empleado.getTelefono());
      Departamento.setText(String.valueOf(empleado.getDepartamento()));
    }                                        

    
    
    
    public void lista() throws SQLException {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("clave");
    model.addColumn("Nombre");
     String url = "jdbc:postgresql://172.17.0.2:5432/Ejemplo";
        String pdw = "password";
        String usr = "postgres";
        Connection con = DriverManager.getConnection(url, usr, pdw);
   
    Statement statement = con.createStatement();
    String query = "SELECT * FROM Departamento"; // Selecciona solo los datos de la tabla Departamento
    ResultSet resultSet = statement.executeQuery(query);
    Object[] departamento = new Object[2];
    model = (DefaultTableModel) jTable1.getModel();

    while (resultSet.next()) {
        departamento[0] = resultSet.getInt("clave");
        departamento[1] = resultSet.getString("nombre");
        model.addRow(departamento);
    }
    jTable1.setModel(model);
}
    

    
    
    
    
    
    
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
           DaoEmpleado daoempleado = new DaoEmpleado();  
             boolean eliminado = daoempleado.eliminar(Integer.parseInt(Clave.getText()));
    
    if (eliminado) {
        JOptionPane.showMessageDialog(this, "Se eliminó correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Error al eliminar el registro", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }                                        

    private void ClaveActionPerformed(java.awt.event.ActionEvent evt) {                                      
Clave.setText("");        // TODO add your handling code here:
    }                                     

    

    // Variables declaration - do not modify                     
    private javax.swing.JTextField Clave;
    private javax.swing.JTextField Departamento;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField Telefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration                   
}
ce.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 *
 * @author francisco
 */
@Entity
@Table(name = "Detalleventa")
public class Detalleventa implements Serializable {
    @Id
     @GeneratedValue(strategy =  GenerationType.SEQUENCE, generator =  "detalleventa_idventa_seq")
    @SequenceGenerator(name = "detalleventa_idventa_seq", sequenceName = "detalleventa_idventa_seq", allocationSize = 1)
    @Column(name = "idLinea")
    private long idLinea;
    @Column
    private int cantidad;
    @Column
    private double precio;
    @Column
    private String producto;
   
 
    @ManyToOne
    @JoinColumn(name = "idventa")
    private Venta venta;
            
    public Venta getVenta() {
        return venta;
    }

    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    public long getIdLinea() {
        return idLinea;
    }

    public void setIdLinea(long idLinea) {
        this.idLinea = idLinea;
    }

    public int getCantidad() {
        return cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public double getPrecio() {
        return precio;
    }

    public void setPrecio(double precio) {
        this.precio = precio;
    }

    public String getProducto() {
        return producto;
    }

    public void setProducto(String producto) {
        this.producto = producto;
    }

}
